name: Add CI to repo

# This GitHub Action Workflow is running on the cloud devcimultiintel cluster
# The tests are run inside of a container with the following software/libraries:
# -intel: 2023.2.0
# -hdf5: 1.14.0
# -netcdf-c: 4.9.2
# -netcdf-fortran: 4.6.0
# -cmake
# -libyaml

on:
  pull_request:
    branches:
      - main

#this should cancel in progress ci runs for the same PR 
#(e.g. a second commit on the same PR comes in while CI is still running)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    if: github.repository == 'NOAA-GFDL/SHiELD_build'
    runs-on: [shieldbuild]
    name: Checkout Code
    steps:
    # It can take a long time (5-15 minutes) to spinup nodes
    # so this salloc will prompt 46 nodes to startup and stay active for 20 min
    # this is enough nodes for the first 17 tests to run in parallel, and we
    # have 17 runners configured.
    - run: salloc --partition=p2 -N 46 -J $GITHUB_SHA sleep 20m &
    - run: /contrib/fv3/SHiELD_build_CI/checkout.sh -b $GITHUB_REF -h $GITHUB_SHA

  build:
    if: github.repository == 'NOAA-GFDL/SHiELD_build'
    runs-on: [shieldbuild]
    name: SOLO SHiELD build
    needs: [checkout]
    strategy:
      fail-fast: true
      max-parallel: 17
      matrix:
        runscript: [/contrib/fv3/SHiELD_build_CI/checkout_fms.sh]
        config: [shield, solo]
        hydro: [sw, nh, hydro]
        bit: [32bit, 64bit]
        mode: [repro, prod, debug]
    steps:
      

  test:
    if: github.repository == 'NOAA-GFDL/SHiELD_build'
    runs-on: [shieldbuild]
    name: SOLO SHiELD test suite
    needs: [checkout, build]
    strategy:
      fail-fast: false
      max-parallel: 17
      matrix:
        runscript: [/contrib/fv3/SHiELD_build_CI/run_test.sh]
        argument:
          # These are placed in order of largest to smallest jobs
          #layout 8,8 needs 8 nodes
          - C512r20.solo.superC
          - C768.sw.BTwave
          #layout 4,8 needs 4 nodes
          - d96_500m.solo.mtn_schar
    
    steps:
      - run: scancel -n $GITHUB_SHA
      - env:
          JOB: ${{ github.sha }}_${{ matrix.test }}
        run: scancel -n $JOB
