#!/bin/sh
#***********************************************************************
#*                   GNU Lesser General Public License
#*
#* This file is part of the SHiELD Build System.
#*
#* The SHiELD Build System free software: you can redistribute it
#* and/or modify it under the terms of the
#* GNU Lesser General Public License as published by the
#* Free Software Foundation, either version 3 of the License, or
#* (at your option) any later version.
#*
#* The SHiELD Build System distributed in the hope that it will be
#* useful, but WITHOUT ANYWARRANTY; without even the implied warranty
#* of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#* See the GNU General Public License for more details.
#*
#* You should have received a copy of the GNU Lesser General Public
#* License along with theSHiELD Build System
#* If not, see <http://www.gnu.org/licenses/>.
#***********************************************************************
#
#  DISCLAIMER: This script is provided as-is and as such is unsupported.
#

. ${MODULESHOME}/init/sh
module load git

export SHiELD_SRC=${PWD%/*}/SHiELD_SRC/

mkdir -p ${SHiELD_SRC}
cd ${SHiELD_SRC}

release="FV3-202204-public"

fv3_release=$release
phy_release=$release
fms_release="2022.01"

git clone -b ${fv3_release}   https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere
git clone -b ${phy_release}   https://github.com/NOAA-GFDL/SHiELD_physics
git clone -b ${fms_release}   https://github.com/NOAA-GFDL/FMS

#Automatic release tracking from Matt M.
echo $release > ../../release
